openapi: 3.0.3
info:
    title: Foxes Knowledge API documentation
    version: 1.0.0
servers:
    - url: http://localhost:8000
tags:
    - name: Auth
paths:
    /api/auth/signin:
        $ref: "./resources/auth.yaml#/SignIn"
    /api/auth/signup:
        $ref: "./resources/auth.yaml#/SignUp"

components:
    securitySchemes:
        BearerAuth:
            $ref: "./schemas/security.yaml"
